application: your-app-id 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /cron
  script: spy.app
  login: admin

- url: /.*
  script: spy.app


libraries:
- name: jinja2
  version: latest
